easy_admin:
    entities:
        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\User
        - App\Entity\Event
        - App\Entity\City
        - App\Entity\Language
        - App\Entity\Participant

